### ISSUE TITLE
Generate dates in particular range

### ISSUE THREAD

**Issue by kuncevich** [webroo/dummy-json#10]
Lets say I want to generate all dates for particular month or year is there any way I can do that?
Currently it is just generating the random dates in specific range but I want to generate all dates for that particular range.

**Comment by webroo** [comment]
Do you mean generate the dates in sequence? Eg: "1 Jan 2010", "2 Jan 2010", "3 Jan 2010", etc...?

Unfortunately this is not something the built-in date helper can do - in fact all the built-in helpers are designed to return random data, not sequences.

However you can try writing your own. Remember that your custom helpers can return whatever value they want, so you could write one that returns a new date every time it's called and keeps track of the number of times it's called using it's own counter. If I have time I'll write a basic example and put it here.

**Comment by kuncevich** [comment]
Yeah it is exactly that. E.g: `{{dateRange '2016-01-01' '2016-01-10'}}` will produce `1 Jan 2016", "2 Jan 2016", "3 Jan 2016", ..., "10 Jan 2016"`.

**Comment by webroo** [comment]
I've put together something that I hope works for you:

```js
var customHelpers = {
  dateRange: function (startDate, options) {
    var date = new Date(startDate);
    date.setDate(date.getDate() + options.data.index);
    return dummyjson.fecha.format(date, 'D MMM YYYY');
  }
};

var template = '{{#repeat 3}}{{dateRange "2016-01-01"}}{{/repeat}}';

var result = dummyjson.parse(template, {helpers: customHelpers});
// 1 Jan 2016
// 2 Jan 2016
// 3 Jan 2016
```

The helper is used like this: `{{dateRange startDate}}`, where `startDate` is a string that represents a date, eg: "2016-01-01". The date automatically increments by 1 day each loop, up to the number of loops defined in the repeat block.

It works by taking the current index of the repeat loop and calculates the number of additional days to add to the start date. The `options` object is automatically given to helpers by handlerbars and contains meta data about the current state of parsing. In this case we use it to find out the current index. The date is then formatted by [fecha](https://github.com/taylorhakes/fecha) before being returned.

It only increments by day right now, but you can swap out the `date.setDate()` for any of the other date function, like `setMonth()` or `setFullYear()` to increment by other time periods.

**Comment by kuncevich** [comment]
@webroo great thanks a lot
