### ISSUE TITLE
Conditional Statements

### ISSUE THREAD

**Issue by jdmagic21** [webroo/dummy-json#17]
Would it be possible to create conditional if/else statements depending on whether or not object properties inside of other properties should contain certain values? For example: 
```
{
    "dummyData": [
    {{#repeat 10}}
    {
        "id": "{{@index}}",
        "qty": "{{int 1 100}}", 
        "desc": "{{lorem 25}}",
        "capAsset": "{{boolean}}",
        "Tag": "IU{{int 0 999}}{{int 0 20}}",
        "images": "http://lorempixel.com/400/200/technics",
        "pickupRequest": {
            {{#if capAsset }}
            "pickup": "true",
            "contact": "{{name}}"
            {{else}}
            "pickup": "false"
            {{/if}}
        }
    }
    {{/repeat}}
    ]
}
```

**Comment by webroo** [comment]
Yes, this should be possible, dummy-json uses Handlebars for it's templating language so everything available in Handlebars is also available to dummy-json. (In fact dummy-json just adds new helper methods to Handlebars, it's actually not that complex or sophisticated.)

The Handlebars `{{#if}}` helper is described in more detail here http://handlebarsjs.com/block_helpers.html#conditionals

And you might want to use it in combination with the default `{{#each}}` or `{{#with}}` helpers, to change the scope of data, as described here http://handlebarsjs.com/block_helpers.html#iterators

And finally the section about ["Using other data"](https://github.com/webroo/dummy-json#using-other-data) in the README of this project shows you how to use custom data in your templates, which might come in handy.
