### ISSUE TITLE
No command-line interface?

### ISSUE THREAD

**Issue by n2liquid** [webroo/dummy-json#2]
It looks like you haven't implemented a command-line interface for this program. I think that would be really useful. Would you like me to implement a proposal CLI? Would you merge it in if it looks good or are you against the idea?

If you're interested, could tell me what you'd like to see in such an interface?

Cheers and thank you for the free-as-in-freedom software :)

**Comment by webroo** [comment]
Basic cli functionality added in 0.0.3.
