### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by kuncevic** [webroo/dummy-json#21]
When running custom helper like per example:
```
var myHelpers = {
  direction: function() {
    // Use dummyjson random to ensure the seeded random number generator is used
    return dummyjson.utils.random() > 0.5 ? 'left' : 'right';
  }
};
var template = '{{direction}}';
var result = dummyjson.parse(template, {helpers: myHelpers}); // Returns "left"
```
all working fine but getting an warning:
`(node:21284) DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

**Comment by webroo** [comment]
Cannot replicate, likely fixed during major version bumps to the handlebars library since this issue was raised.
