### ISSUE TITLE
Typo in type definition (v3.0.0)

### ISSUE THREAD

**Issue by simon368** [webroo/dummy-json#35]
The extra semicolon in the type definition (https://github.com/webroo/dummy-json/blob/master/index.d.ts#L54) throws the following error:

```
node_modules/dummy-json/index.d.ts:54:2 - error TS1036: Statements are not allowed in ambient 
contexts.

54 };
```

**Comment by webroo** [comment]
Thanks for letting me know! Fixed in 3.0.1
