### ISSUE TITLE
Memory Leak Issue while writing unit test

### ISSUE THREAD

**Issue by shirishvasu** [webroo/dummy-json#7]
Our team used to dummy-json to generate JSON using templates. It was giving response as expected.

var comp_data = dummyjson.parse(template, {data: data}); 

While writing test using supertest(^1.1.0), and mocha(^2.2.3), we are getting the following error:-
 
Error: global leaks detected:partials

Can you check why is that so?

**Comment by webroo** [comment]
This is a bug in dummy-json v0.0.3 and has been fixed in the latest version (1.0.0). I would urge you to update, although please be aware the API has changed slightly (hence major release bump). Please see the readme for more information, especially the bit at the bottom about upgrading.
